### ISSUE TITLE
pip3 install doesn't work

### ISSUE THREAD

**Issue by joshiatharva93** [scottfrazer/hermes#54]
Thanks for this amazing library.

I would like to report a problem:
`pip3 install hermes-parser` does not work at the moment.

```
(attachment-pG6NvoxY) bash-3.2$ pip3 install hermes-parser
Collecting hermes-parser
  Using cached https://files.pythonhosted.org/packages/bd/65/2de767906320535271e2302009ebc931355c323450099af70881fbf330c3/hermes-parser-1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/ln/grnjhvzj7v5gbpwf81prtpj80000gq/T/pip-install-ztinvao2/hermes-parser/setup.py", line 1, in <module>
        import distribute_setup
    ModuleNotFoundError: No module named 'distribute_setup'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/ln/grnjhvzj7v5gbpwf81prtpj80000gq/T/pip-install-ztinvao2/hermes-parser/
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(attachment-pG6NvoxY) bash-3.2$
```

**Comment by illusional** [comment]
Hey @aaj5956, if you checkout the repository and run `pip install .` within the directory, this works okay. I think the module on `PyPi` is very out of date (last release [Nov 2012](https://pypi.org/project/hermes-parser/#history)). 

I don't know if @scottfrazer is still watching this repo, but if so I'm happy to add some stuff to the `.travisci` file to auto-deploy on tags.

**Comment by scottfrazer** [comment]
Oh jeez I’m sorry I didn’t respond to the original message!  Any changes are welcome, or I can ressurect this project at some point 😄
